[package]
name = "tcpeek"
version = "0.1.0"
edition = "2021"
authors = ["sharvul"]
description = "A utility to capture the first N packets from TCP sessions"

[dependencies]
pcap = "2.2.0"
clap = { version = "4.5.36", features = ["derive"] }
ctrlc = "3.4.6"
